
/**************************************************************
 *	
 *	BadBlood, 8 bit, 11025Hz,
 *	1 channel, 2313008 bytes/channel
 *	Total Size: 1 * 2313008 + 4 (header) = 2313052 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mckenzieelliott/Documents/GT/2261/Lab09_McKenzie Elliott 2/BadBlood.wav
 *	Time-stamp: Thu Mar 17 13:48:28 2016
 *	
 **************************************************************/

#ifndef __BADBLOODH__
#define __BADBLOODH__

#define BADBLOODFREQ 11025
#define BADBLOODLEN 2313008

extern const unsigned char BadBlood[2313008];

#endif /* __BADBLOODH__ */
