
/**************************************************************
 *	
 *	Foot, 8 bit, 11025Hz,
 *	1 channel, 6333 bytes/channel
 *	Total Size: 1 * 6333 + 4 (header) = 6377 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mckenzieelliott/Documents/GT/2261/Lab09_McKenzie Elliott 2/Foot.wav
 *	Time-stamp: Fri Mar 18 14:23:03 2016
 *	
 **************************************************************/

#ifndef __FOOTH__
#define __FOOTH__

#define FOOTFREQ 11025
#define FOOTLEN 6333

extern const unsigned char Foot[6333];

#endif /* __FOOTH__ */
