
/**************************************************************
 *	
 *	FootStep, 8 bit, 11025Hz,
 *	1 channel, 12238 bytes/channel
 *	Total Size: 1 * 12238 + 4 (header) = 12282 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mckenzieelliott/Documents/GT/2261/Lab09_McKenzie Elliott 2/FootStep.wav
 *	Time-stamp: Fri Mar 18 14:10:37 2016
 *	
 **************************************************************/

#ifndef __FOOTSTEPH__
#define __FOOTSTEPH__

#define FOOTSTEPFREQ 11025
#define FOOTSTEPLEN 12238

extern const unsigned char FootStep[12238];

#endif /* __FOOTSTEPH__ */
