
/**************************************************************
 *	
 *	smack, 8 bit, 11025Hz,
 *	1 channel, 4563 bytes/channel
 *	Total Size: 1 * 4563 + 4 (header) = 4607 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mckenzieelliott/Documents/GT/2261/smack.wav
 *	Time-stamp: Wed Apr 20 01:02:12 2016
 *	
 **************************************************************/

#ifndef __SMACKH__
#define __SMACKH__

#define SMACKFREQ 11025
#define SMACKLEN 4563

extern const unsigned char smack[4563];

#endif /* __SMACKH__ */
